//go:build darwin

package ipv6packet

import (
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"syscall"
	"time"
	"unsafe"
)

type bpfPacketDevice struct {
	fd        int
	buffer    []byte
	pending   [][]byte
	diagnosed bool
}

var bpfHeaderMinimum = int(unsafe.Offsetof(syscall.BpfHdr{}.Hdrlen) + unsafe.Sizeof(syscall.BpfHdr{}.Hdrlen))

func openBPFPacketDevice(interfaceName string, mtu int) (frameDevice, error) {
	fd, err := openAvailableBPF()
	if err != nil {
		return nil, err
	}
	closeOnError := true
	defer func() {
		if closeOnError {
			_ = syscall.Close(fd)
		}
	}()
	if err := syscall.CheckBpfVersion(fd); err != nil {
		return nil, fmt.Errorf("check BPF version: %w", err)
	}
	// Darwin allocates the BPF buffers when BIOCSETIF attaches the device.
	// BIOCSBLEN must therefore run first; setting it after the interface is
	// attached returns EINVAL on a real macOS BPF descriptor.
	requested := (mtu + ethernetHeaderSize + syscall.SizeofBpfHdr + 3) * 64
	bufferSize, err := syscall.SetBpfBuflen(fd, requested)
	if err != nil {
		return nil, fmt.Errorf("set BPF buffer size: %w", err)
	}
	if err := syscall.SetBpfInterface(fd, interfaceName); err != nil {
		return nil, fmt.Errorf("attach BPF to %s: %w", interfaceName, err)
	}
	datalink, err := syscall.BpfDatalink(fd)
	if err != nil {
		return nil, fmt.Errorf("read BPF datalink: %w", err)
	}
	if datalink != syscall.DLT_EN10MB {
		return nil, fmt.Errorf("interface %s BPF datalink is %d, expected Ethernet", interfaceName, datalink)
	}
	if err := syscall.SetBpfImmediate(fd, 1); err != nil {
		return nil, fmt.Errorf("enable immediate BPF delivery: %w", err)
	}
	if err := syscall.SetBpfHeadercmpl(fd, 1); err != nil {
		return nil, fmt.Errorf("enable complete BPF Ethernet headers: %w", err)
	}
	// The broker only injects frames received from downstream clients. Keeping
	// locally generated multicast, RA, and reply traffic in the BPF stream makes
	// it harder to distinguish real ingress and risks re-reading frames written
	// by WriteFrame. BIOCSSEESENT=0 retains remotely originated frames while
	// excluding packets generated by this Mac.
	if err := setBPFSeeSent(fd, false); err != nil {
		return nil, fmt.Errorf("restrict BPF capture to incoming frames: %w", err)
	}
	if err := syscall.SetBpfTimeout(fd, &syscall.Timeval{Sec: 0, Usec: int32((250 * time.Millisecond) / time.Microsecond)}); err != nil {
		return nil, fmt.Errorf("set BPF read timeout: %w", err)
	}
	filter := []syscall.BpfInsn{
		*syscall.BpfStmt(syscall.BPF_LD|syscall.BPF_H|syscall.BPF_ABS, 12),
		*syscall.BpfJump(syscall.BPF_JMP|syscall.BPF_JEQ|syscall.BPF_K, etherTypeIPv6, 0, 1),
		*syscall.BpfStmt(syscall.BPF_RET|syscall.BPF_K, 0xffff),
		*syscall.BpfStmt(syscall.BPF_RET|syscall.BPF_K, 0),
	}
	if err := syscall.SetBpf(fd, filter); err != nil {
		return nil, fmt.Errorf("install IPv6 BPF filter: %w", err)
	}
	closeOnError = false
	return &bpfPacketDevice{fd: fd, buffer: make([]byte, bufferSize)}, nil
}

func setBPFSeeSent(fd int, enabled bool) error {
	value := uint32(0)
	if enabled {
		value = 1
	}
	_, _, errno := syscall.Syscall(syscall.SYS_IOCTL, uintptr(fd), uintptr(syscall.BIOCSSEESENT), uintptr(unsafe.Pointer(&value)))
	if errno != 0 {
		return errno
	}
	return nil
}

func openAvailableBPF() (int, error) {
	var lastErr error
	for index := 0; index < 256; index++ {
		path := fmt.Sprintf("/dev/bpf%d", index)
		fd, err := syscall.Open(path, syscall.O_RDWR|syscall.O_CLOEXEC, 0)
		if err == nil {
			return fd, nil
		}
		if errors.Is(err, syscall.EBUSY) || errors.Is(err, syscall.EACCES) {
			lastErr = err
			continue
		}
		if errors.Is(err, syscall.ENOENT) {
			break
		}
		lastErr = err
	}
	if lastErr == nil {
		lastErr = os.ErrNotExist
	}
	return -1, fmt.Errorf("open an available /dev/bpf device: %w", lastErr)
}

func (d *bpfPacketDevice) ReadFrame() ([]byte, error) {
	for len(d.pending) == 0 {
		n, err := syscall.Read(d.fd, d.buffer)
		if err != nil {
			if errors.Is(err, syscall.EINTR) || errors.Is(err, syscall.EAGAIN) {
				continue
			}
			return nil, err
		}
		if n == 0 {
			continue
		}
		if !d.diagnosed && n >= syscall.SizeofBpfHdr {
			header := (*syscall.BpfHdr)(unsafe.Pointer(&d.buffer[0]))
			log.Printf("OpenSurge IPv6 BPF read bytes=%d header=%d captured=%d packet=%d struct=%d", n, header.Hdrlen, header.Caplen, header.Datalen, syscall.SizeofBpfHdr)
			d.diagnosed = true
		}
		d.pending = parseBPFFrames(d.buffer[:n])
	}
	frame := d.pending[0]
	d.pending = d.pending[1:]
	return frame, nil
}

func parseBPFFrames(buffer []byte) [][]byte {
	frames := make([][]byte, 0, 8)
	for offset := 0; offset+syscall.SizeofBpfHdr <= len(buffer); {
		header := (*syscall.BpfHdr)(unsafe.Pointer(&buffer[offset]))
		start := offset + int(header.Hdrlen)
		end := start + int(header.Caplen)
		// bh_hdrlen describes the wire ABI and may exclude the trailing Go
		// struct padding. On current arm64 macOS it is 18 while
		// syscall.SizeofBpfHdr is 20; requiring the padded size drops every
		// valid captured frame.
		if int(header.Hdrlen) < bpfHeaderMinimum || start > len(buffer) || end > len(buffer) || end < start {
			break
		}
		frames = append(frames, append([]byte(nil), buffer[start:end]...))
		offset += bpfWordAlign(int(header.Hdrlen) + int(header.Caplen))
	}
	return frames
}

func bpfWordAlign(length int) int { return (length + 3) &^ 3 }

func (d *bpfPacketDevice) WriteFrame(frame []byte) error {
	n, err := syscall.Write(d.fd, frame)
	if err != nil {
		return err
	}
	if n != len(frame) {
		return io.ErrShortWrite
	}
	return nil
}

func (d *bpfPacketDevice) Close() error {
	if d.fd < 0 {
		return nil
	}
	err := syscall.Close(d.fd)
	d.fd = -1
	return err
}
